# Generated by Django 5.0.2 on 2024-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('GN', 'General notification'), ('NP', 'New Post'), ('NC', 'New Comment'), ('NL', 'New Like'), ('FC', 'Friendship status changed')], default='GN', max_length=2),
        ),
    ]
