# Generated by Django 5.0.2 on 2024-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hook_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
