# Generated by Django 5.0.2 on 2024-08-22 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_views',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts_manager.posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
