# Generated by Django 5.0.2 on 2024-08-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0002_rename_comment_content_comments_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts_manager.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
