# Generated by Django 5.0.2 on 2024-09-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0003_remove_posts_comments_alter_comments_content_and_more'),
        ('posts_manager', '0003_remove_posts_comments_remove_posts_likes_and_more'),
    ]

    operations = [
    ]
