# Generated by Django 5.0.2 on 2024-09-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_manager', '0004_merge_20240911_1223'),
        ('posts_manager', '0004_merge_20240911_1251'),
    ]

    operations = [
    ]
