# Generated by Django 5.0.2 on 2024-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='invited',
            field=models.BooleanField(default=False),
        ),
    ]
