# Generated by Django 5.0.2 on 2024-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_manager', '0002_friendship_invited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='invited',
            new_name='is_Friend',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(default=False),
        ),
    ]
