# Generated by Django 5.0.2 on 2024-08-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_manager', '0003_rename_invited_friendship_is_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
