# Generated by Django 5.0.2 on 2024-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_manager', '0004_alter_friendship_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
